#ifndef ERROR_MESSAGE_H
#define GENERAL_MESSAGE "\nSub Commands: \n"                                                                                   \
			"ls\t\tlist all account details\n"                                                                     \
			"add\t\tadd a new account\n"                                                                           \
			"change\t\tchange details of an account\n"                                                             \
			"search\t\tsearch for an account\n"                                                                    \
			"delete\t\tdelete an account\n"                                                                        \
			"help\t\tdisplay this message\n\n"                                                                     \
			"Use cman <sub-command> help for details about a sub command\n\n"                                      \
			"Note: cman checks for the credential database file path from the environment variable $CMAN_DBFILE\n" \
			"      If that environment variable is not found it defaults to $HOME/.creds.db\n"

#define ADD_MESSAGE "Usage: "                                                                                                \
		    "cman add <account_name> {auto|no-auto}\n\n"                                                             \
		    "cman add <account_name> auto\t\tAutomatically generates password\n"                                     \
		    "cman add <account_name> no-auto\t\tPassword given by user\n\n"                                          \
		    "cman add --batch <filename>\t\tAdd multiple account details from a batch file <filename>\n\n"           \
		    "Rules for batch file:\n"                                                                                \
		    "1.Each line has details of a single account i.e account name, user name and passowrd"                   \
		    " separated by commas eg accName,uName,pass\n"                                                           \
		    "2.Empty lines are ignored\n"                                                                            \
		    "3.Spaces within the line are treated as part of the respective field\n"                                 \
		    "4.If it is required that program generates the password, use ? as a placeholder for the password i.e. " \
		    "aName,uName,?\n\n"

#define CHANGE_MESSAGE "Usage: cman change <account_name> <option>\n"                           \
		       "Options to Change: \n"                                                  \
		       "user\t\t\tChange user name for given account\n"                         \
		       "name\t\t\tChange the name for the account\n"                            \
		       "pass {auto|no-auto}\tChange password for account given\n"               \
		       "master\t\t\tChange the master password for the credential database\n\n" \
		       "Change password options: \n"                                            \
		       "auto\t\tPassword automatically generated by program\n"                  \
		       "no-auto\t\tPassword provided by user\n"

#define SEARCH_MESSAGE "Usage:\n cman search <account>\t\tSearch details for given account\n"

#define DELETE_MESSAGE "Usage:\n cman delete <account>\t\tDelete the details for given account\n"

#define LS_MESSAGE "Usage:\n cman ls \t\tList details of all accounts\n"

#endif
