#ifndef ERROR_MESSAGE_H 
#define GENERAL_MESSAGE "Sub Commands: \n" \
			"ls\t\tlist all account details\n"\
			"add\t\tadd a new account\n"\
			"change\t\tchange details of an account\n"\
			"search\t\tsearch for an account\n"\
			"delete\t\tdelete an account\n"\
			"help\t\tdisplay this message\n\n"\
			"Use cman <sub-command> help for details about a sub command\n"
			
#define ADD_MESSAGE "Usage: "\
		    "cman add <account_name> {auto|no-auto}\n\n"\
		    "cman add <account_name> auto\t\tAutomatically generates password\n"\
		    "cman add <account_name> no-auto\t\tPassword given by user\n"

#define CHANGE_MESSAGE  "Usage: cman change <account_name> <option>\n"\
		        "Options to Change: \n"\
		        "user\t\t\tChange user name for given account\n"\
			"name\t\t\tChange the name for the account\n"\
			"pass {auto|no-auto}\tChange password for account given\n"\
			"master\t\t\tChange the master password for the credential database\n\n"\
			"Change password options: \n"\
			"auto\t\tPassword automatically generated by program\n"\
			"no-auto\t\tPassword provided by user\n"

#define SEARCH_MESSAGE "Usage:\n cman search <account>\t\tSearch details for given account\n"

#define DELETE_MESSAGE "Usage:\n cman delete <account>\t\tDelete the details for given account\n"

#define LS_MESSAGE "Usage:\n cman ls \t\tList details of all accounts\n"


#endif

